SpellLuckWXSmall/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SpellLuckWXSmall.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

SpellLuckWXSmall/Pages/ErrorNull.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SpellLuckWXSmall.Pages
{
    public class ErrorNullModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SpellLuckWXSmall/Pages/GoodsListShow.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SpellLuckWXSmall.Models;
using Microsoft.AspNetCore.Mvc;
using Tools.DB;
using MongoDB.Driver;
using MongoDB.Bson;

namespace SpellLuckWXSmall.Pages
{
    public class GoodsListShowModel : PageModel
    {
        public List<GoodsModel> GoodsModelList { get; set; }
        private int pageSize = 5;
        public int PageIndex { get; set; }
        public int PageCount { get; set; }
        private int maxPageShow = 10;
        public int MaxPageShow { get => maxPageShow; }
        public int PageSize { get => pageSize; }

        public GoodsModel SelectedGoods { get; set; }
        public void OnGet()
        {
           SetPage(0);
        }
        public async Task<IActionResult> OnGetGoPageAsync(int pageIndex)
        {
            if (pageIndex == -1 || pageIndex == PageCount)
            {
                return RedirectToPage();
            }
            await Task.Run(()=> {
                SetPage(pageIndex);
            });

            return Page();
        }

        private void SetPage(int pageIndex)
        {
      
               PageIndex = pageIndex;
               var filter = Builders<GoodsModel>.Filter.Empty;
               var find = new MongoDBTool().GetMongoCollection<GoodsModel>().Find(filter);
               var count = find.Count();
               PageCount = ((int)count / pageSize) + (count % pageSize == 0 ? 0 : 1);
               GoodsModelList = find.Skip(PageIndex * pageSize).Limit(PageSize).ToList();
         
        }

        public async Task<IActionResult> OnGetDelGoods(string goodsId)
        {
           await Task.Run(()=> {

                var filter = Builders<GoodsModel>.Filter.Eq(x => x.GoodsID, new ObjectId(goodsId));
                new MongoDBTool().GetMongoCollection<GoodsModel>().DeleteOne(filter);
            });
         
            return RedirectToPage();
        }
    }
}

SpellLuckWXSmall/Pages/GoodsPush.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Hosting;
using SpellLuckWXSmall.Models;
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Mvc;
using Tools;
using System.IO;
using MongoDB.Bson;
using Tools.ResponseModels;
using Microsoft.AspNetCore.Http;
using System.Threading;
using Tools.Models;
using Tools.DB;
using System.ComponentModel.DataAnnotations;

namespace SpellLuckWXSmall.Pages
{
    public class GoodsPushModel : PageModel
    {
        public string Message { get; set; }

        private IHostingEnvironment hostingEnvironment;
        public GoodsPushModel(IHostingEnvironment environment)
        {
            this.hostingEnvironment = environment;
        }
        public void OnGet()
        {
            Message = "Your application description page.";
        }
        [BindProperty]
        public GoodsModel GoodsModel { get; set; }


        [Required]
        [BindProperty]
        public List<IFormFile> MainImages { get; set; }

        [Required]
        [BindProperty]
        public List<IFormFile> OtherImages { get; set; }
        [Required]
        [BindProperty]
        public string GoodsColor { get; set; }
        [Required]
        [BindProperty]
        public string GoodsRule { get; set; }
        [BindProperty]
        [Required]
        public IFormFile ListImage { get; set; }
        public async Task<IActionResult> OnPostSubmitGoodsAsync()
        {

            if (CheckHasNull())
            {
                return RedirectToPage("/ErrorNull");
            }
            BaseResponseModel<string> responseModel = new BaseResponseModel<string>();
            if (MainImages.Count > 5)
            {
                MainImages.RemoveRange(5, MainImages.Count - 5);
            }
            if (GoodsModel.GoodsMainImages == null)
            {
                GoodsModel.GoodsMainImages = new List<FileModel<string[]>>();
            }
            if (GoodsModel.GoodsOtherImages == null)
            {
                GoodsModel.GoodsOtherImages = new List<FileModel<string[]>>();
            }
            await SaveImage(ListImage);
            await SaveImages(MainImages, GoodsModel.GoodsMainImages);
            await SaveImages(OtherImages, GoodsModel.GoodsOtherImages);
            saveColor();
            saveRule();
            if (GoodsModel.GoodsPayType == 2)
            {
                GoodsModel.GoodsPrice = new decimal(0.01);
            }
            try
            {
                new MongoDBTool().GetMongoCollection<GoodsModel>().InsertOne(GoodsModel);
                responseModel.StatusCode = (int)ActionParams.code_ok;
            }
            catch (Exception)
            {
                responseModel.StatusCode = (int)ActionParams.code_error;
                throw;
            }

            return RedirectToPage("/GoodsPushFinish");
        }

        private bool CheckHasNull()
        {
            bool hasNull = false;
            if (
                OtherImages == null || OtherImages.Count == 0
               || MainImages == null || MainImages.Count == 0
               || ListImage == null
                || string.IsNullOrEmpty(GoodsColor)
                || string.IsNullOrEmpty(GoodsRule)
                || string.IsNullOrEmpty(GoodsModel.GoodsTitle)
                || string.IsNullOrEmpty(GoodsModel.GoodsDetail)
                || GoodsModel.GoodsOldPrice == 0
                )
            {
                hasNull = true;
            }
            return hasNull;
        }

        private void saveRule()
        {
            var rules = GoodsRule.Split("\r\n");
            if (GoodsModel.GoodsRule == null)
            {
                GoodsModel.GoodsRule = new List<string>();
            }
            for (int i = 0; i < rules.Length; i++)
            {
                GoodsModel.GoodsRule.Add(rules[i]);
            }
        }

        private void saveColor()
        {
            var colors = GoodsColor.Split("\r\n");
            if (GoodsModel.GoodsColor == null)
            {
                GoodsModel.GoodsColor = new List<string>();
            }
            for (int i = 0; i < colors.Length; i++)
            {
                GoodsModel.GoodsColor.Add(colors[i]);
            }
        }

        private async Task<long> SaveImage(IFormFile listImage)
        {
            return await Task.Run(() =>
            {

                long size = 0;
                if (listImage != null)
                {
                    var filename = ContentDispositionHeaderValue
                                    .Parse(listImage.ContentDisposition)
                                    .FileName
                                    .Trim('"');
                    string saveDir = $@"{ConstantProperty.BaseDir}{ConstantProperty.GoodsImagesDir}";
                    if (!Directory.Exists(saveDir))
                    {
                        Directory.CreateDirectory(saveDir);
                    }
                    filename = filename.Substring(filename.LastIndexOf("."));
                    string saveName = ConstantProperty.GoodsImagesDir + ObjectId.GenerateNewId().ToString() + $@"{filename}";
                    filename = ConstantProperty.BaseDir + saveName;
                    size += listImage.Length;
                    using (FileStream fs = System.IO.File.Create(filename))
                    {
                        listImage.CopyTo(fs);
                        fs.Flush();

                    }
                    ParamsCreate3Img params3Img = new ParamsCreate3Img() { FileName = filename, FileDir = ConstantProperty.GoodsImagesDir };
                    params3Img.OnFinish += fileModel =>
                    {
                        if (fileModel.FileID == ObjectId.Empty)
                        {
                            fileModel.FileID = ObjectId.GenerateNewId();
                        }
                        GoodsModel.GoodsListImage = fileModel;
                    };
                    ImageTool.Create3Img(params3Img);
                }
                return size;
            });
        }

        private async Task<long> SaveImages(List<IFormFile> sourceImages, List<FileModel<string[]>> container)
        {
            return await Task.Run(() =>
            {

                long size = 0;
                foreach (var file in sourceImages)
                {
                    var filename = ContentDispositionHeaderValue
                                    .Parse(file.ContentDisposition)
                                    .FileName
                                    .Trim('"');
                    string saveDir = $@"{ConstantProperty.BaseDir}{ConstantProperty.GoodsImagesDir}";
                    if (!Directory.Exists(saveDir))
                    {
                        Directory.CreateDirectory(saveDir);
                    }
                    filename = filename.Substring(filename.LastIndexOf("."));
                    string saveName = ConstantProperty.GoodsImagesDir + ObjectId.GenerateNewId().ToString() + $@"{filename}";
                    filename = ConstantProperty.BaseDir + saveName;
                    size += file.Length;
                    using (FileStream fs = System.IO.File.Create(filename))
                    {
                        file.CopyTo(fs);
                        fs.Flush();

                    }
                    ParamsCreate3Img params3Img = new ParamsCreate3Img() { FileName = filename, FileDir = ConstantProperty.GoodsImagesDir };
                    params3Img.OnFinish += fileModel =>
                    {
                        if (fileModel.FileID == ObjectId.Empty)
                        {
                            fileModel.FileID = ObjectId.GenerateNewId();
                        }
                        container.Add(fileModel);
                    };
                    //ThreadPool.QueueUserWorkItem(new WaitCallback(ImageTool.Create3Img), params3Img);
                    //Thread thread = new Thread(new ParameterizedThreadStart(ImageTool.Create3Img));
                    //thread.IsBackground = false;
                    //thread.Start(params3Img);
                    ImageTool.Create3Img(params3Img);
                }
                return size;
            });



        }
    }

}

SpellLuckWXSmall/Pages/GoodsPushFinish.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SpellLuckWXSmall.Pages
{
    public class GoodsPushFinishModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SpellLuckWXSmall/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SpellLuckWXSmall.Models;
using Tools.DB;
using MongoDB.Driver;
using SpellLuckWXSmall.Interceptors;
using System.Text;

namespace SpellLuckWXSmall.Pages
{
    public class IndexModel : PageModel
    {
        [BindProperty]
        public CompanyAccountModel CAM { get; set; }
        MongoDBTool mongo = new MongoDBTool();

        public CompanyAccountModel CAMOut { get; set; }
        private CompanyModel company;
        public bool ErrorAccount { get; set; }
        public bool ErrorVerify { get; set; }
        public void OnGet()
        {
            company = GetCompany();

            if (company != null && company.CompanyAccountList != null && company.CompanyAccountList.Count != 0)
            {
                CAMOut = company.CompanyAccountList.FirstOrDefault();
            }
            else
            {
                CAMOut = null;
            }
        }

        private CompanyModel GetCompany()
        {
            return mongo.GetMongoCollection<CompanyModel>().Find(Builders<CompanyModel>.Filter.Empty).FirstOrDefault();

        }

        public async Task<IActionResult> OnPostLogin()
        {

            bool isSuccess;
            CAMOut = GetCAM();
            if (CAMOut == null)
            {
                if (!CAM.CompanyAccountPassword.Equals(CAM.CompanyAccountVerifyPassword))
                {
                    ErrorVerify = true;
                    OnGet();
                    return Page();
                }
                isSuccess = await DoSetAdmin();
            }
            else
            {
                isSuccess = await DoLogin();
            }
            if (isSuccess)
            {
                HttpContext.Session.Set("CompanyAccountName", Encoding.UTF8.GetBytes(CAM.CompanyAccountName.ToString()));
                return RedirectToPage("/OrderListShow");
            }
            else
            {
                OnGet();
                ErrorAccount = true;
                return Page();
            }
        }

        private async Task<bool> DoLogin()
        {
            return await Task.Run(() =>
            {
                CAMOut = GetCAM();
                if (CAM.CompanyAccountPassword.Equals(CAMOut.CompanyAccountPassword) && CAM.CompanyAccountName.Equals(CAMOut.CompanyAccountName))
                {
                    return true;
                }
                return false;
            });

        }

        private CompanyAccountModel GetCAM()
        {
            var company = GetCompany();
         
            if (company==null||company.CompanyAccountList == null || company.CompanyAccountList.Count == 0)
            {
                return null;
            }
            return company.CompanyAccountList.FirstOrDefault();
        }

        private async Task<bool> DoSetAdmin()
        {
            return await Task.Run(
                () =>
                {
                    List<CompanyAccountModel> list = new List<CompanyAccountModel>() { CAM };
                    company = GetCompany();
                    if (company != null && company.CompanyAccountList == null)
                    {
                        mongo.GetMongoCollection<CompanyModel>().UpdateOne(x => x.CompanyID.Equals(company.CompanyID), Builders<CompanyModel>.Update.Set(x => x.CompanyAccountList, list));
                    }
                    else if (company == null)
                    {
                        mongo.GetMongoCollection<CompanyModel>().InsertOne(new CompanyModel() { TimeOpenJack = new TimeOpenJack() { JackPotTimerHour = AppConstData.JackPotTimerHour, JackPotTimerMinute = AppConstData.JackPotTimerMinute }, CompanyAccountList = list });
                    }
                    return true;
                }
                );
        }
    }
}

SpellLuckWXSmall/Pages/ErrorNull.cshtml
@page
@model ErrorNullModel
@{
    ViewData["Title"] = "错误";
    ViewData["Index"] = -1;

}
<h1>不能含有空值</h1>

SpellLuckWXSmall/Pages/GoodsListShow.cshtml
@page
@model GoodsListShowModel
@using SpellLuckWXSmall.Models
@{
    ViewData["Title"] = "商品展示";
    ViewData["Index"] = 3;

    int pageIndex = Model.PageIndex;
}
<div class="jumbotron">
    <h1>@ViewData["Title"]</h1>
</div>
<div class="marketing">
    <div class="row">
        @if (Model.GoodsModelList != null && Model.GoodsModelList.Count > 0)
        {
            @foreach (var item in Model.GoodsModelList)
            {
                <div class="col-lg-4">
                    <figure style="width:350px;height:200px;overflow:hidden;">
                        <img class="img-responsive" src="/file/FileDownload?fileUrl=@item.GoodsListImage.FileUrlData[1]" />
                    </figure>
                    <h2 class="text-primary">@item.GoodsTitle</h2>
                    <p class="text-info">@item.GoodsDetail</p>
                    <p class="bg-danger">
                    原价：<span class="text-danger">@item.GoodsOldPrice</span> ￥ &nbsp;  
                    团价：<span class="text-danger">@item.GoodsPrice</span> ￥ &nbsp; 
                    购买方式：<span class="text-danger">@(item.GoodsPayType == 0 ? "2人团购" : item.GoodsPayType == 1 ? "3-6人团购" : "一分夺宝")</span></p>
                    <p><button class="btn btn-danger" data-target="#delGoodsModal" onclick="setDelGoodsId('@item.GoodsID.ToString()')" data-toggle="modal">删除</button></p>
                    @* asp-page-handler="delGoods" asp-route-goodsID="@item.GoodsID.ToString()" *@
                </div>
            }
        }
    </div>
</div>
<br />
<div class="col-xs-12 col-lg-9">
    <ul class="pagination pagination-lg">

        @if (Model.PageIndex != 0)
            {
            <li><a asp-page-handler="goPage" asp-route-pageIndex="@(Model.PageIndex - 1)">&laquo;</a></li>
        }
        @for (int i = 1; i < 10 && i < Model.PageCount + 1; i++)
            {
                if (Model.PageIndex + i <= Model.PageCount)
                {
                <li><a asp-page-handler="goPage" asp-route-pageIndex="@(Model.PageIndex + i - 1)">@(Model.PageIndex + i)</a></li>
            }
        }
        @if (Model.PageIndex + 1 < Model.PageCount)
            {
            <li><a asp-page-handler="goPage" asp-route-pageIndex="@(Model.PageIndex + 1)">&raquo;</a></li>
        }
    </ul>
</div>

<br style="clear:both;"/>

<div class="modal fade" id="delGoodsModal" tabindex="-1" role="dialog" aria-labelledby="sendGoodsTitle" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="sendGoodsTitle">删除商品</h4>
            </div>
            <div class="modal-body">
                <div>
                    删除后不能恢复，请谨慎！
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消操作</button>
                <button type="button" onclick="delGoods()" class="btn btn-danger">删 除</button>
            </div>
        </div>
    </div>
</div>


<script>
    var delGoodsId = "";
    function delGoods() {
        location.href = "/GoodsListShow?goodsID=" + delGoodsId + "&handler=delGoods";
    }
    function setDelGoodsId(goodsId) {
        delGoodsId = goodsId;
    }
</script>

SpellLuckWXSmall/Pages/GoodsPush.cshtml
@page
@model GoodsPushModel
@{
    ViewData["Title"] = "商品添加";
    ViewData["Index"] = 2;

}
<div class="jumbotron">
    <h1>@ViewData["Title"]</h1>
</div>
<form class="form" method="post" asp-page-handler="submitGoods" enctype="multipart/form-data">
    <div class="row">
        <div class="col-xs-6 col-sm-3">
            <label for="goodsTitle">商品标题</label>
            <input id="goodsTitle" asp-for="GoodsModel.GoodsTitle" maxlength="20" class="form-control col-xs-6 col-sm-4" type="text" placeholder="标题（最多20字）" />
        </div>
        <div class="col-xs-6 col-sm-3">
            <label for="goodsPayType">商品购买类型</label>
            <select id="goodsPayType" onchange="OnPayTypeChanged(this)" class="form-control col-xs-6 col-sm-3" asp-for="GoodsModel.GoodsPayType">
                <option value="0">2人拼团</option>
                <option value="1">3-6人拼团</option>
                <option value="2">1分夺宝</option>
            </select>
        </div>
        <div class="col-xs-6 col-sm-3" id="goodsPriceRow">
            <label for="goodsPrice">商品团价</label>
            <input id="goodsPrice" asp-for="GoodsModel.GoodsPrice" class="form-control col-xs-6 col-sm-4" placeholder="价格（实例12.42）" />
        </div>
        <div class="col-xs-6 col-sm-3">
            <label for="goodsOldPrice">商品原价</label>
            <input id="goodsOldPrice" asp-for="GoodsModel.GoodsOldPrice" class="form-control col-xs-6 col-sm-4" placeholder="价格（实例12.42）" />
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-xs-6 col-sm-4">
            <label for="goodsDetail">商品简介</label>
            <textarea id="goodsDetail" asp-for="GoodsModel.GoodsDetail" maxlength="2000" class="form-control" rows="6" placeholder="简介字数2000以内"></textarea>
        </div>
        <div class="col-xs-6 col-sm-4">
            <label class="" for="goodsColor">商品颜色(每行一个)</label>
            <textarea id="goodsColor" asp-for="GoodsColor" class="form-control" placeholder="颜色（每行一个，不能有空行，最后不能加回车）" rows="6"></textarea>
        </div>
        <div class="col-xs-6 col-sm-4">
            <label class="" for="goodsRule">商品尺寸(每行一个)</label>
            <textarea id="goodsRule" asp-for="GoodsRule" class="form-control" rows="6" placeholder="尺寸（每行一个，不能有空行，最后不能加回车）"></textarea>
        </div>
    </div>

    <br />
    <div class="row">
        <div class="col-xs-6 col-sm-4">
            <input type="file" asp-for="ListImage" max="5" id="goodsListPic" onchange="loadFile(this)" class="hidden" />
            <div class="input-append">
                <a class="btn btn-default" onclick="$('input[id=goodsListPic]').click();">选择商品列表图片</a>
                <span>未选择（必须选择）</span>
            </div>
        </div>
        <div class="col-xs-6 col-sm-4">
            <input type="file" asp-for="MainImages" multiple max="5" onchange="loadFile(this,5)" id="goodsHomePic" class="hidden" />
            <div class="input-append">
                <a class="btn btn-default" onclick="$('input[id=goodsHomePic]').click();">选择商品主图</a>
                <span>未选择（必须选择）</span>
            </div>
        </div>
        <div class="col-xs-6 col-sm-4">
            <input type="file" asp-for="OtherImages" onchange="loadFile(this)" class="hidden" id="goodsOtherPic" multiple />
            <div class="input-append">
                <a class="btn btn-default" onclick="$('input[id=goodsOtherPic]').click();">选择商品其他图片</a>
                <span>未选择（必须选择）</span>
            </div>
        </div>
    </div>
    <br />
    <br />
    <div class="row" style="padding-right:15px;">
        <button class="btn btn-lg btn-success col-xs-6 col-sm-4 pull-right" type="submit">提 交</button>
    </div>
</form>
<br />
<br />
<br />
<script>
    function OnPayTypeChanged(obj) {
        var priceRow = $("#goodsPriceRow");
        if ($(obj).val() == 2) {
            priceRow.hide();
        } else {

            priceRow.show();
        }
    }
    function loadFile(o, maxLength) {
        if (maxLength != undefined && o.files.length > maxLength) {
            alert("最多可以选择" + maxLength + "张");
            return;
        }
        var text = o.files.length == 1 ? o.files[0].name : o.files.length + "张图片";
        $(o).next().find("span").html(text);
    }
</script>

SpellLuckWXSmall/Pages/GoodsPushFinish.cshtml
@page
@model GoodsPushFinishModel
@{
    ViewData["Title"] = "成功添加商品";
    ViewData["Index"] = -1;

}
<h1>商品添加成功</h1>
<a class="btn btn-default" asp-page="/GoodsPush">继续添加</a>

SpellLuckWXSmall/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "登录";
    ViewData["Index"] = -1000;
}
<style>
    body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #eee;
    }

    .form-signin {
        max-width: 330px;
        padding: 15px;
        margin: 0 auto;
    }

        .form-signin .form-signin-heading,
        .form-signin .checkbox {
            margin-bottom: 10px;
        }

        .form-signin .checkbox {
            font-weight: normal;
        }

        .form-signin .form-control {
            position: relative;
            height: auto;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
            padding: 10px;
            font-size: 16px;
        }

            .form-signin .form-control:focus {
                z-index: 2;
            }

        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
</style>
    <form class="form-signin" asp-page-handler="login" method="post">
        <h2 class="form-signin-heading">管理员@(Model.CAMOut == null ? "用户设置" : "登录")</h2>
        <label for="inputEmail" class="sr-only">用户名</label>
        <input type="text" id="inputEmail" asp-for="CAM.CompanyAccountName" class="form-control" placeholder="用户名" required autofocus>
        <label for="inputPassword" class="sr-only">密码</label>
        <input type="password" id="inputPassword" asp-for="CAM.CompanyAccountPassword" class="form-control" placeholder="密码" required>
        <label for="inputVerifyPassword" class='sr-only @(Model.CAMOut == null ?"":"hidden")'>确认密码</label>
        <input type="password" id="inputVerifyPassword" asp-for="CAM.CompanyAccountVerifyPassword" 
               class='form-control @(Model.CAMOut == null ?"":"hidden")' placeholder="确认密码">
       
        <p class=' form-control  label-danger @(Model.ErrorAccount?"":"hidden")'>用户名或者密码有误！</p>
        <p class=' form-control  label-danger @(Model.ErrorVerify?"":"hidden")'>两次密码不一致！</p>

        <button class="btn btn-lg btn-primary btn-block" type="submit">@(Model.CAMOut == null ? "提交设置" : "登录")</button>
    </form>

SpellLuckWXSmall/Pages/PayList.cshtml
@page
@model PayListModel
@{ ViewData["Title"] = "已付款列表";
    ViewData["Index"] = 4;
}
<div class="jumbotron">
    <h1>@ViewData["Title"]</h1>
</div>
<h2 class="sub-header">已付款列表</h2>
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <td>微信订单号</td>
                <td>订单商品</td>
                <td>商品标题</td>
                <td>购买人</td>
                <td>头像</td>
                <td>商品颜色</td>
                <td>商品尺寸</td>
                <td>商品类型</td>
                <td>订单金额</td>
                <td>付款时间</td>
            </tr>
        </thead>
        <tbody>

            @for (int i = 0; i < Model.AllJackPotList.Count(); i++)
            {

                @for(int j=0;j<Model.AllJackPotList[i].Participator.Count();j++){
                    <tr>
                        <td style="vertical-align:middle">@Model.AllJackPotList[i].Participator[j].WXOrderId</td>
                        <td style="vertical-align:middle"><img width="90" height="60" src="/file/FileDownload?fileUrl=@Model.AllJackPotList[i].JackGoods.GoodsListImage.FileUrlData[2]" /></td>
                        <td style="vertical-align:middle;max-width:100px;">@Model.AllJackPotList[i].JackGoods.GoodsTitle</td>
                        <td style="vertical-align:middle">@Model.AllJackPotList[i].Participator[j].AccountName</td>
                        <td style="vertical-align:middle"><img width="60" height="60" class="img-circle" src="@Model.AllJackPotList[i].Participator[j].AccountAvatar" /></td>


                        <td style="vertical-align:middle">@Model.AllJackPotList[i].Participator[j].GoodsColor</td>
                        <td style="vertical-align:middle">@Model.AllJackPotList[i].Participator[j].GoodsRule</td>
                        <td style="vertical-align:middle">@(Model.AllJackPotList[i].JackGoods.GoodsPayType == 0 ? "2人拼团" : @Model.AllJackPotList[i].JackGoods.GoodsPayType == 1 ?"多人拼团" : "一分夺宝")</td>
                        <td style="vertical-align:middle">@Model.AllJackPotList[i].JackPotPrice</td>
                        <td style="vertical-align:middle">@Model.AllJackPotList[i].CreateTime.ToString("yyyy/MM/dd HH:mm:ss")</td>
                    </tr>
                    }
            }

        </tbody>
    </table>
</div>